export type MenuItem = { name: string; size?: string; price: string };
export type MenuCategory = { id: string; title: string; subtitle: string; items: MenuItem[]; note?: string };

export const MENU: MenuCategory[] = [
  {
    id: "softdrinks", title: "Softdrinks", subtitle: "Erfrischungen",
    items: [
      { name: "Coca Cola", size: "0,33l", price: "3,90 €" },
      { name: "Fanta", size: "0,33l", price: "3,90 €" },
      { name: "Sprite", size: "0,33l", price: "3,90 €" },
      { name: "Paulaner Spezi", size: "0,50l", price: "3,90 €" },
      { name: "Schwarze Dose", size: "0,33l", price: "4,50 €" },
      { name: "Moloko", size: "0,33l", price: "4,50 €" },
      { name: "Red Bull", size: "0,25l", price: "3,90 €" },
      { name: "Wasser Still / Sprudel", size: "0,33l", price: "3,90 €" },
      { name: "Wasser Still / Sprudel", size: "0,75l", price: "6,90 €" },
      { name: "Schweppes", size: "0,20l", price: "3,50 €" },
      { name: "Saft Pur", size: "0,40l", price: "4,50 €" },
      { name: "Saftschorlen", size: "0,40l", price: "3,90 €" },
      { name: "Fresh Juice Orange", size: "0,20l", price: "2,90 €" },
    ],
  },
  {
    id: "tee", title: "Tee", subtitle: "Heiße Aufgüsse",
    items: [
      { name: "Hausgemachter EisTee", price: "3,90 €" },
      { name: "Kamillen Tee", price: "3,40 €" },
      { name: "Früchte Tee", price: "3,40 €" },
      { name: "Schwarz Tee", price: "3,40 €" },
      { name: "Zitrone – Ingwer Tee", price: "3,40 €" },
      { name: "MIRAÉ Tee", price: "3,90 €" },
    ],
  },
  {
    id: "alkoholfrei", title: "Alkoholfreie Getränke", subtitle: "Signature Mocktails",
    items: [
      { name: "Lillet Berry", price: "6,90 €" },
      { name: "Hugo", price: "6,90 €" },
      { name: "Limetten Spritz", price: "6,90 €" },
      { name: "Peach Lady", price: "6,90 €" },
      { name: "Coconut Kiss", price: "7,90 €" },
      { name: "Virgin Caipi", price: "7,90 €" },
      { name: "FloBi", price: "7,90 €" },
      { name: "Virgin Mojito", price: "7,90 €" },
      { name: "Virgin Sunrise", price: "7,90 €" },
      { name: "Spring Paradis", price: "7,90 €" },
    ],
    note: "Weitere Aperitifs / Cocktails auf Anfrage",
  },
  {
    id: "kaffee", title: "Kaffee", subtitle: "Die Espresso-Bar",
    items: [
      { name: "Espresso", price: "2,20 €" },
      { name: "Espresso Macchiato", price: "2,50 €" },
      { name: "Doppio Espresso", price: "3,50 €" },
      { name: "Doppio Macchiato", price: "3,70 €" },
      { name: "Kaffee Crema", price: "3,00 €" },
      { name: "Cappuccino", price: "3,20 €" },
      { name: "Milchkaffee", price: "3,80 €" },
      { name: "Latte Macchiato", price: "3,90 €" },
      { name: "Ice Kaffee", price: "4,90 €" },
      { name: "Ice Latte", price: "4,90 €" },
      { name: "Chai Latte", price: "3,60 €" },
      { name: "Matcha Latte", price: "4,20 €" },
      { name: "Ice Matcha Latte", price: "4,90 €" },
      { name: "Heisse Schokolade", price: "3,90 €" },
      { name: "Heisse Weiße Schokolade", price: "3,90 €" },
    ],
    note: "Optional auch mit Hafermilch · +0,50 €",
  },
  {
    id: "snacks", title: "Snacks & Desserts", subtitle: "Kleine Begleiter",
    items: [
      { name: "Obstteller", price: "8,90 €" },
      { name: "Nachos mit Dip", price: "4,90 €" },
      { name: "Nachos mit Käse überbacken", price: "5,90 €" },
      { name: "Sucuk-Käse Toast", price: "5,90 €" },
      { name: "Popcorn Homemade XL", price: "4,90 €" },
      { name: "Dips extra je", price: "0,80 €" },
      { name: "Schokoladensoufflé", price: "4,90 €" },
      { name: "Pistaziensoufflé", price: "5,90 €" },
    ],
  },
  {
    id: "shisha", title: "Shisha", subtitle: "Das Herzstück",
    items: [
      { name: "Black Nana", price: "14 €" },
      { name: "Love 66", price: "14 €" },
      { name: "Lemon Chill", price: "14 €" },
      { name: "Ice Kaktus", price: "14 €" },
      { name: "Löwenherz", price: "14 €" },
      { name: "Eisbonbon", price: "14 €" },
      { name: "Traube Minze", price: "14 €" },
      { name: "African Queen", price: "14 €" },
      { name: "Cold Peach", price: "14 €" },
      { name: "MIRAÉ Spezial", price: "18 €" },
    ],
    note: "Weitere Sorten auf Anfrage",
  },
];
